version: '2'

services:
  web:
    build: ./web
    expose:
      - "5000"
    depends_on:
      - database

  database:
    image: postgres:10
    volumes:
      - /var/lib/postgresql
    expose:
      - "5432"
